# Numpy Introduction

In [ ]:
# Install numpy using pip
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
# Import necessary libraries
import numpy as np


# What is an Array?


An array is a data structure that can hold multiple values of the same type. It is a collection of items stored at contiguous memory locations. The main advantage of using arrays is that they allow you to store and manipulate large amounts of data efficiently.


In [21]:
a= np.arange(6)
print(a)
a.shape
a.dtype
type(a)

[0 1 2 3 4 5]


numpy.ndarray

In [24]:
a2=a[np.newaxis, :]
print(a2)
a2.shape
a2.dtype
type(a2)

[[0 1 2 3 4 5]]


numpy.ndarray

In [6]:
a3=a2[np.newaxis, :]
print(a3)
a3.shape

[[[0 1 2 3 4 5]]]


(1, 1, 6)

## Creating array with numpy

In [11]:
a=np.array([1, 2, 3, 4, 5,6,7])
b=np.array([(1, 2, 3, 4, 5,6,7), (4,5,6,7,8, 9, 10)])
print(a)
a.shape


[1 2 3 4 5 6 7]


(7,)

In [12]:

print(b)
b.shape

[[ 1  2  3  4  5  6  7]
 [ 4  5  6  7  8  9 10]]


(2, 7)

# Intialize arrays

In [14]:
zeros=np.zeros((3, 4)) # 3 rows, 4 columns
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [15]:
ones=np.ones((3, 4)) # 3 rows, 4 columns
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [17]:
full = np.full((3, 4), 5) # 3 rows, 4 columns, filled with 5
print(full)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [19]:
# creating an identity matrix
identity = np.eye(5)
print(identity) 
identity.dtype

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


dtype('float64')